version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: nocodelowcode-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    environment:
      - VITE_API_URL=${VITE_API_URL}
    container_name: nocodelowcode-frontend
    ports:
      - "5173:5173"   # serve uses 5173, matches EXPOSE in Dockerfile
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
